"use client"

import { useState } from "react"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Loader2, Check, X, MessageCircle, Clock, Users } from "lucide-react"
import { toast } from "sonner"
import { useRouter } from "next/navigation"

interface RequestsClientProps {
    initialPending: any[]
    initialAccepted: any[]
    userId: string
}

export function RequestsClient({ initialPending, initialAccepted, userId }: RequestsClientProps) {
    const [pending, setPending] = useState(initialPending)
    const [accepted, setAccepted] = useState(initialAccepted)
    const [processing, setProcessing] = useState<string | null>(null)
    const router = useRouter()

    const handleRespond = async (requestId: string, action: "ACCEPT" | "REJECT") => {
        setProcessing(requestId)
        try {
            const res = await fetch("/api/connections/respond", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ requestId, action })
            })

            if (!res.ok) throw new Error("Failed to process request");

            if (action === "REJECT") {
                setPending(prev => prev.filter(r => r.id !== requestId))
                toast.success("Request ignored")
            } else {
                // ACCEPT
                toast.success("Connection accepted!")
                // Optimistic Update: Move to Accepted? Or just refresh.
                // Moving is complex because we need the new connectionId generated by server (logic says generateSTId).
                // So easiest is to refresh or reload data.
                router.refresh()
                // Helper: remove from pending locally to immediate feedback
                setPending(prev => prev.filter(r => r.id !== requestId))
            }
        } catch (error) {
            toast.error("Something went wrong")
        } finally {
            setProcessing(null)
        }
    }

    const openWhatsApp = async (connectionId: string) => {
        try {
            const res = await fetch(`/api/connections/${connectionId}/whatsapp`)
            if (!res.ok) throw new Error("No link")
            const data = await res.json()
            if (data.link) {
                window.open(data.link, "_blank")
            } else {
                toast.error("Could not generate WhatsApp link")
            }
        } catch (error) {
            toast.error("Error opening WhatsApp")
        }
    }

    return (
        <Tabs defaultValue="inbox" className="w-full">
            <TabsList className="grid w-full grid-cols-2 max-w-[400px] mb-8">
                <TabsTrigger value="inbox" className="relative">
                    Inbox
                    {pending.length > 0 && (
                        <span className="absolute -top-1 -right-1 flex h-4 w-4 items-center justify-center rounded-full bg-destructive text-[10px] text-destructive-foreground">
                            {pending.length}
                        </span>
                    )}
                </TabsTrigger>
                <TabsTrigger value="connections">Connections</TabsTrigger>
            </TabsList>

            <TabsContent value="inbox" className="space-y-6">
                {pending.length === 0 ? (
                    <div className="text-center p-16 border rounded-lg bg-muted/40 flex flex-col items-center gap-4">
                        <Users className="h-12 w-12 text-muted-foreground opacity-20" />
                        <h3 className="font-semibold text-lg">No pending requests</h3>
                        <p className="text-muted-foreground">Your inbox is clear.</p>
                    </div>
                ) : (
                    <div className="grid gap-4 md:grid-cols-2">
                        {pending.map((req) => (
                            <Card key={req.id}>
                                <CardHeader className="pb-3 flex flex-row gap-4 items-start space-y-0">
                                    <Avatar className="h-10 w-10">
                                        <AvatarImage src={req.fromUser?.image} />
                                        <AvatarFallback>{(req.senderName || "?")[0]}</AvatarFallback>
                                    </Avatar>
                                    <div className="flex-1 space-y-1">
                                        <CardTitle className="text-base flex items-center justify-between">
                                            {req.senderName}
                                            <Badge variant="secondary" className="text-xs font-normal">
                                                {req.senderRole}
                                            </Badge>
                                        </CardTitle>
                                        <CardDescription className="text-xs">
                                            {req.purpose} &bull; {new Date(req.createdAt).toLocaleDateString()}
                                        </CardDescription>
                                    </div>
                                </CardHeader>
                                <CardContent className="pb-3 text-sm italic text-muted-foreground">
                                    "{req.message}"
                                </CardContent>
                                <CardFooter className="flex justify-end gap-2 pt-0 pb-4">
                                    <Button variant="ghost" size="sm" onClick={() => handleRespond(req.id, "REJECT")} disabled={!!processing}>
                                        Ignore
                                    </Button>
                                    <Button size="sm" onClick={() => handleRespond(req.id, "ACCEPT")} disabled={!!processing}>
                                        {processing === req.id && <Loader2 className="mr-2 h-3 w-3 animate-spin" />}
                                        Accept
                                    </Button>
                                </CardFooter>
                            </Card>
                        ))}
                    </div>
                )}
            </TabsContent>

            <TabsContent value="connections" className="space-y-6">
                {accepted.length === 0 ? (
                    <div className="text-center p-16 border rounded-lg bg-muted/40 flex flex-col items-center gap-4">
                        <Users className="h-12 w-12 text-muted-foreground opacity-20" />
                        <h3 className="font-semibold text-lg">No connections yet</h3>
                    </div>
                ) : (
                    <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                        {accepted.map((conn) => {
                            // Determine 'other' user to display
                            const isMeSender = conn.fromUserId === userId;
                            const otherUser = isMeSender ? conn.toUser : conn.fromUser;
                            const otherName = isMeSender ? conn.toUser?.name : conn.senderName; // senderName might be snapshot
                            // Better to use User relation if available
                            const displayName = otherUser?.name || "User";

                            return (
                                <Card key={conn.id}>
                                    <CardHeader className="pb-3 flex flex-row gap-4 items-center space-y-0">
                                        <Avatar>
                                            <AvatarImage src={otherUser?.image} />
                                            <AvatarFallback>{displayName[0]}</AvatarFallback>
                                        </Avatar>
                                        <div>
                                            <CardTitle className="text-base">{displayName}</CardTitle>
                                            <div className="text-xs text-muted-foreground font-mono">{conn.connectionId || "Active"}</div>
                                        </div>
                                    </CardHeader>
                                    <CardFooter className="pt-0 pb-4">
                                        <Button className="w-full gap-2 bg-green-600 hover:bg-green-700 text-white" onClick={() => openWhatsApp(conn.connectionId || conn.id)}>
                                            <MessageCircle className="h-4 w-4" />
                                            Chat on WhatsApp
                                        </Button>
                                    </CardFooter>
                                </Card>
                            )
                        })}
                    </div>
                )}
            </TabsContent>
        </Tabs>
    )
}
